name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "dailynews"
database_id = "56d93b7a-bec3-4ae2-be1b-a9c8c46aa775"
